name: flutter_mapas_osm
description: "Trabalhando com mapas"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  battery_plus: ^6.2.1
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  geolocator: ^14.0.0
  latlong2: ^0.9.1
  provider: ^6.1.5
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
